title: "Zhiheng Chen's Personal Webpage"
email: zc548@cornell.edu | ericczh1@outlook.com
description: >-
  Zhiheng Chen's academic webpage.
baseurl: ""
url: "https://Zhiheng-Chen.github.io"
theme: jekyll-theme-cayman

plugins:
  - jekyll-feed
  
author:
  name: "Zhiheng Chen"
  avatar: "/assets/img/avatar.jpg"
  bio: "MS student at Cornell MAE"
  location: "Ithaca, NY"